[package]
name = "dup-img-finder"
version = "0.1.1"
edition = "2021"
description = "Duplicate image finder"
license = "MIT"
repository = "https://github.com/Thaumy/dup-img-finder"
keywords = ["image"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
image-compare = "0.3.0"
image = "0.24.7"
image_hasher = "1.2.0"
colored = "2.0.4"
num_cpus = "1.16.0"
crossbeam = "0.8.2"
base64-url = "2.0.0"
clap = { version = "4.4.3", features = ["derive"] }
